### ISSUE TITLE
[Bug]: Metadata not loading

### ISSUE THREAD

**Issue by casparfritzen** [iotaledger/explorer#321] opened 2022-06-02 19:25 UTC
### Issue description

https://explorer.alphanet.iotaledger.net/alphanet/block/0x9d233a7b3bcd0357dd32fc7e8d29484aaf511e50c2056c7774bfec4100653f05

gives you this error:

Failed to retrieve metadata. There was a problem communicating with the API. SyntaxError: The string did not match the expected pattern.

### Expected behaviour

show metadata

### Actual behaviour

Failed to retrieve metadata. There was a problem communicating with the API. SyntaxError: The string did not match the expected pattern.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msarcev** [comment] 2022-06-08 13:50
Unfortunately the linked example doesn't work anymore. I think it's because the alphanet got bumped to new version. We need to find a way to reproduce this issue on a different block.

**Comment by laumair** [comment] 2022-06-09 10:56
@casparfritzen

> Unfortunately the linked example doesn't work anymore. I think it's because the alphanet got bumped to new version. We need to find a way to reproduce this issue on a different block.

**Comment by Thoralf-M** [comment] 2022-06-13 08:59
With https://explorer.alphanet.iotaledger.net/alphanet/block/6816c4eb9240bd4c13cda19fd6bedf239baa0148f30eea8dfd017aa8b95b0300 I get `Failed to retrieve metadata. There was a problem communicating with the API. SyntaxError: Unexpected end of JSON input`

**Comment by msarcev** [comment] 2022-06-14 07:37
I think this issue is a duplicate of https://github.com/iotaledger/explorer/issues/337 actually.

**Closed** 2022-06-16 11:49 UTC
Labels: priority:1, type:fix, network:shimmer, bug report
