### ISSUE TITLE
[Improvement UX]: Report the size in bytes of data fields of an Output

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/explorer#951] opened 2024-01-11 09:01 UTC
### Issue description

Currently there is no way to know what is the size in bytes of the data field of an Output when displayed in the Explorer. For instance, the state metadata field of an Alias Output.

### Expected behaviour

Have an additional information stating the number of bytes consumed by the data field

Example: Status (244 bytes) or Status (1.04Kb) 

### Actual behaviour

No info is provided. 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Open a view of an Output that have data fields, for instance Alias Output

![Screenshot 2024-01-11 at 09 59 09](https://github.com/iotaledger/explorer/assets/67736750/658e0ada-085d-4a3c-810f-5ae06b1e8093)

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmcanterafonseca-iota** [comment] 2024-01-11 09:06
@begonaalvarezd

**Comment by begonaalvarezd** [comment] 2024-01-11 09:30
@jmcanterafonseca-iota I believe this is a duplicate of https://github.com/iotaledger/explorer/issues/828?

**Comment by begonaalvarezd** [comment] 2024-02-13 18:53
dup of https://github.com/iotaledger/explorer/issues/828

**Closed by begonaalvarezd** 2024-02-13 18:53 UTC
