### ISSUE TITLE
[Bug]: Messages are listed multiple times

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/explorer#128] opened 2022-02-09 15:41 UTC
### Issue description

Messages are listed multiple times

### Expected behaviour

A message should only be there once

### Actual behaviour

Messages are listed multiple times

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Open /mainnet/addr/iota1qzvatgke57tuuuud3fvjg0jkgqah366gte2rjm0jxfgudmfcfftasjyf4yu

### Errors

![image](https://user-images.githubusercontent.com/46689931/153235257-79862e77-c056-4891-94f1-6179a3829c3f.png)

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laumair** [comment] 2022-02-10 10:52
Duplicate of #97

**Closed by laumair** 2022-02-10 10:52 UTC
Labels: v2, type:bug
