### ISSUE TITLE
[Bug]: Navbar blur issue in firefox

### ISSUE THREAD

**Issue by coodos** [iotaledger/explorer#150] opened 2022-02-10 10:33 UTC
### Issue description

The `background-filter` blur doesn't work on firefox and the navbar looks weird and shows the contents of messages when scrolled

### Expected behaviour

The message IDs are hidden

### Actual behaviour

![Screen Shot 2022-02-10 at 16 01 47](https://user-images.githubusercontent.com/69296233/153388975-59e09bf3-963d-4bc7-a65b-70ddef13887b.png)

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by r-c-k** [comment] 2022-02-10 11:16
Duplicate of #131

**Closed** 2022-02-10 11:27 UTC
Labels: v2, type:bug
