### ISSUE TITLE
[Bug]: Problem with implicit NftId 

### ISSUE THREAD

**Issue by PAFsec** [iotaledger/explorer#387] opened 2022-07-09 18:35 UTC
### Issue description

Hello team,

When freshly minted (NTFOutput not consumed afterwards), the NftId is wrongly showing under the endpoint "alphanet/nft-address/<my_NTF_address>".
This bug, seems to make it impossible to see the other Output for this address.

### Expected behaviour

Implicit NFTId should be calculated (BLAKE2b-256 of the NftOutput), so we could also see the other outputs for this address (BasicOutput for insntance)

### Actual behaviour

It is trying to read the explicit NFT that does not exists as it just got minted:

NFT Address: rms1zqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq8ktl8x
NFT Id: 0x0000000000000000000000000000000000000000000000000000000000000000

Making it bug when displaying other Outputs (none are showing).
As soon as the NftId becomes explicit (the NftOutput got consumed at least once), everything works as expected.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1) Mint an NFT and do not consume the NftOutput
2) go to the explorer for the NFT address just minted

### Errors

```shell
-
```

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msarcev** [comment] 2022-07-27 12:38
Couldn't reproduce this with newly minted NFT. Maybe it was fixed in some other commit.
Can you try to reproduce it again on testnet ?

**Comment by PAFsec** [comment] 2022-07-27 18:42
Just tried on testnet, and it works perfectly now!
Thanks :)

**Comment by PAFsec** [comment] 2022-07-30 11:40
@msarcev, same problem with implicit AliasId ;)
exemple: https://explorer.shimmer.network/testnet/addr/rms1pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq0tjsfd

**Closed** 2022-08-25 07:20 UTC
